apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: temtum256/temtumc-be:v1
        resources:
          requests:
            memory: "800Mi"
            cpu: "1000m"
        envFrom:
        - secretRef:
            name: dotfile-secret-be
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30008
